params/imu: {
mag_offset_x: -7.05, mag_offset_y: -24.59, mag_offset_z: -70.06,
mag_soft_iron_ix: 1.013, mag_soft_iron_iy: -0.031, mag_soft_iron_iz: -0.005,
mag_soft_iron_jx: -0.031, mag_soft_iron_jy: 0.978, mag_soft_iron_jz: 0.013,
mag_soft_iron_kx: -0.005, mag_soft_iron_ky: 0.013, mag_soft_iron_kz: 1.010
}
