params/imu: {
mag_offset_x: 22.63, mag_offset_y: -27.74, mag_offset_z: -78.66,
mag_soft_iron_ix: 0.980, mag_soft_iron_iy: -0.025, mag_soft_iron_iz: 0.010,
mag_soft_iron_jx: -0.025, mag_soft_iron_jy: 0.994, mag_soft_iron_jz: 0.024,
mag_soft_iron_kx: 0.010, mag_soft_iron_ky: 0.024, mag_soft_iron_kz: 1.029
}