params/imu: {
mag_offset_x: 14.38, mag_offset_y: -29.27, mag_offset_z: -34.21,
mag_soft_iron_ix: 0.978, mag_soft_iron_iy: -0.025, mag_soft_iron_iz: 0.009,
mag_soft_iron_jx: -0.025, mag_soft_iron_jy: 1.002, mag_soft_iron_jz: 0.006,
mag_soft_iron_kx: 0.009, mag_soft_iron_ky: 0.006, mag_soft_iron_kz: 1.021
}
