params/imu: {
calibration_mode: 2,
gain_acc: 0.02,
gain_mag: 0.005,
bias_alpha: 0.1,
sensor_read_rate: 100,
output_rate_divider: 2,
adaptive_gain: true,
bias_estimation: true,
gfsr: 0,
afsr: 2,
world_frame: 0,
use_mag: true,
imu_frame_id: "imu_link",
mag_frame_id: "imu_link"
}
