params/imu: {
mag_offset_x: -11.88, mag_offset_y: -48.52, mag_offset_z: -68.05,
mag_soft_iron_ix: 0.985, mag_soft_iron_iy: -0.041, mag_soft_iron_iz: 0.021,
mag_soft_iron_jx: -0.041, mag_soft_iron_jy: 1.002, mag_soft_iron_jz: 0.014,
mag_soft_iron_kx: 0.021, mag_soft_iron_ky: 0.014, mag_soft_iron_kz: 1.016
}
