params/imu: {
mag_offset_x: 24.03, mag_offset_y: -27.36, mag_offset_z: -77.99,
mag_soft_iron_ix: 1.006, mag_soft_iron_iy: -0.033, mag_soft_iron_iz: 0.009,
mag_soft_iron_jx: -0.033, mag_soft_iron_jy: 0.978, mag_soft_iron_jz: 0.029,
mag_soft_iron_kx: 0.009, mag_soft_iron_ky: 0.029, mag_soft_iron_kz: 1.019
}