params/imu: {
mag_offset_x: 27.69, mag_offset_y: 75.44, mag_offset_z: 86.67,
mag_soft_iron_ix: 0.977, mag_soft_iron_iy: -0.034, mag_soft_iron_iz: -0.016,
mag_soft_iron_jx: -0.034, mag_soft_iron_jy: 1.017, mag_soft_iron_jz: -0.001,
mag_soft_iron_kx: -0.016, mag_soft_iron_ky: -0.001, mag_soft_iron_kz: 1.007
}
